"""empty message

Revision ID: 1af1418a10f6
Revises:
Create Date: 2020-10-05 20:07:10.397050

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '1af1418a10f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_unique_constraint(None, 'app_settings', ['id'])
    # op.create_unique_constraint(None, 'db_bet', ['id'])
    # op.create_unique_constraint(None, 'db_chain_event', ['id'])
    # op.create_unique_constraint(None, 'db_withdraw', ['id'])
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'db_withdraw', type_='unique')
    # op.drop_constraint(None, 'db_chain_event', type_='unique')
    # op.drop_constraint(None, 'db_bet', type_='unique')
    # op.drop_constraint(None, 'app_settings', type_='unique')
    # ### end Alembic commands ###
    pass
