"""alter referral table

Revision ID: 2c3d7677a530
Revises: 88d6d87bd8a4
Create Date: 2021-08-09 16:10:19.108058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c3d7677a530'
down_revision = '88d6d87bd8a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('db_referral', sa.Column('network_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'db_referral', 'db_user', ['user_address', 'network_id'], ['address', 'network_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'db_referral', type_='foreignkey')
    op.drop_column('db_referral', 'network_id')
    # ### end Alembic commands ###
