"""alter referral table

Revision ID: 4e70fbdb2ef1
Revises: 2c3d7677a530
Create Date: 2021-08-09 20:16:09.365534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e70fbdb2ef1'
down_revision = '2c3d7677a530'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
