"""empty message

Revision ID: 6e53a32e903f
Revises: 947b0e97633c
Create Date: 2020-10-05 20:49:43.960480

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '6e53a32e903f'
down_revision = '947b0e97633c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('db_bet', sa.Column('fee_amount', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('db_bet', 'fee_amount')
    # ### end Alembic commands ###
    pass
