"""empty message

Revision ID: 85e93286bd1c
Revises: 6e53a32e903f
Create Date: 2020-10-06 02:12:08.453896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85e93286bd1c'
down_revision = '6e53a32e903f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('db_user', 'eth_balance',
    #            existing_type=sa.BIGINT(),
    #            type_=sa.Numeric(),
    #            existing_nullable=True)
    # op.alter_column('db_user', 'usdt_balance',
    #            existing_type=sa.BIGINT(),
    #            type_=sa.Numeric(),
    #            existing_nullable=True)
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('db_user', 'usdt_balance',
    #            existing_type=sa.Numeric(),
    #            type_=sa.BIGINT(),
    #            existing_nullable=True)
    # op.alter_column('db_user', 'eth_balance',
    #            existing_type=sa.Numeric(),
    #            type_=sa.BIGINT(),
    #            existing_nullable=True)
    # ### end Alembic commands ###
    pass
