"""empty message

Revision ID: 947b0e97633c
Revises: 1af1418a10f6
Create Date: 2020-10-05 20:23:27.758604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '947b0e97633c'
down_revision = '1af1418a10f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('app_settings', sa.Column('maintenance', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###
    pass

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('app_settings', 'maintenance')
    # ### end Alembic commands ###
    pass
